version: "3"

services:
  ztlme-postgres:
    image: postgres:latest
    container_name: ztlme-postgres
    environment:
      - POSTGRES_DB=ztlme_dev
      - POSTGRES_USER=ztlme_dev
      - POSTGRES_PASSWORD=ztlme_dev
    ports:
      - "5432:5432"  # Make sure the host port is intended to be 5433
    volumes:
      - postgres-ztlme-data:/var/lib/postgresql/data
    restart: on-failure

volumes:
  postgres-ztlme-data:
